Repository euroargodev/argopy, pull requests merged in 2023-05, with the labels that each got.

#261 indexstore to handle the BGC Argo profile index
  argopy/stores/argo_index_pa.py
  argopy/stores/argo_index_pd.py
  argopy/stores/argo_index_proto.py
  argopy/tests/test_data/mocked_file_index.pkl
  argopy/tests/test_stores.py
  argopy/tests/test_stores_fsspec.py
  argopy/tests/test_stores_index.py
  argopy/utilities.py
  docs/api-hidden.rst
  docs/metadata_fetching.rst
  docs/requirements.txt
  docs/whats-new.rst
Labels: enhancement, backends, argo-BGC

#208 Xarray backend to open Argo Netcdf files
  .gitignore
  argopy/tests/helpers/utils.py
  argopy/tests/test_stores_index.py
  argopy/tests/test_utilities.py
  argopy/utilities.py
  argopy/xarray.py
  cli/llworkflows
  cli/rm_runs_in_workflow
  docs/api-hidden.rst
  docs/api.rst
  docs/install.rst
  docs/whats-new.rst
  requirements.txt
  setup.py
Labels: enhancement, backends

#268 Access to the ADMT pdf documentation
  argopy/__init__.py
  argopy/utilities.py
  docs/api-hidden.rst
  docs/api.rst
  docs/metadata_fetching.rst
  docs/whats-new.rst
Labels: forQCexpert, documentation

#273 provision-with-micromamba is deprecated
  .github/workflows/pytests-upstream.yml
  .github/workflows/pytests.yml
Labels: internals, ignore-for-release

#270 Promote index store to frontend feature
  argopy/__init__.py
  argopy/stores/__init__.py
  argopy/stores/argo_index.py
  argopy/stores/argo_index_deprec.py
  argopy/stores/argo_index_pa.py
  argopy/stores/argo_index_pd.py
  argopy/stores/argo_index_proto.py
  argopy/tests/test_stores_index.py
  docs/api-hidden.rst
  docs/api.rst
  docs/whats-new.rst
Labels: enhancement, internals

#274 Fix failed #270
  argopy/data_fetchers/gdacftp_data.py
  argopy/stores/argo_index_pa.py
  argopy/stores/argo_index_pd.py
  ci/requirements/py3.8-all-free.yml
  ci/requirements/py3.8-core-free.yml
  ci/requirements/py3.9-all-free.yml
  ci/requirements/py3.9-core-free.yml
  docs/metadata_fetching.rst
  docs/whats-new.rst
Labels: internals, ignore-for-release
